[build]
  functions = "netlify/functions"
  command = "npm install" # optional, if using build command

[dev]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
